version: "3.9"


services:
  bdd:
    image: philippecortez/animalia-bdd
    volumes:
      - "animalia_bdd:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=4nimaliA83
      - POSTGRES_USER=animalia
    ports:
      - "5432:5432"

  app-serveur:
    image: philippecortez/animalia-serveur
    ports:
      - "8080:8080"
    depends_on:
      - bdd


volumes:
  animalia_bdd: